// REUNIFY Synthetic Seed Data
// Demonstrates the Arun Madurai scenario + multi-district disaster cases
// Marked: data_origin = 'synthetic'

import {
  MissingPersonCase,
  SourceConnection,
  SourceRecord,
  Candidate,
  CandidateEvidenceItem,
  Investigation,
  InvestigationStep,
  AgentEvent,
  AuditLog,
  NotificationItem,
} from '../types';

export const SEED_SOURCE_CONNECTIONS: SourceConnection[] = [
  {
    id: 'conn-shelter-01',
    name: 'State Disaster Shelter Registry (SDMA-ShelterNet)',
    source_type: 'shelter',
    adapter_key: 'mock_shelter',
    endpoint_url: 'https://api.shelternet.sdma.gov.in/v1',
    status: 'active',
    is_enabled: true,
    records_count: 1420,
    last_synced_at: new Date(Date.now() - 4 * 60000).toISOString(),
    config: { refresh_interval_min: 5, auto_fetch: true },
    data_origin: 'synthetic',
    created_at: '2026-09-28T04:00:00Z',
    updated_at: '2026-09-30T06:00:00Z',
  },
  {
    id: 'conn-hospital-01',
    name: 'Integrated Health & Emergency Trauma Network (HIMS)',
    source_type: 'hospital',
    adapter_key: 'mock_hospital',
    endpoint_url: 'https://hims-emergency.health.gov.in/api/v2',
    status: 'active',
    is_enabled: true,
    records_count: 875,
    last_synced_at: new Date(Date.now() - 2 * 60000).toISOString(),
    config: { include_wristband_tags: true, triaged_only: false },
    data_origin: 'synthetic',
    created_at: '2026-09-28T04:00:00Z',
    updated_at: '2026-09-30T06:30:00Z',
  },
  {
    id: 'conn-helpline-01',
    name: 'Central Distress & Helpline Triage (1070 / 1077)',
    source_type: 'helpline',
    adapter_key: 'mock_helpline',
    endpoint_url: 'https://triage.helpline1070.in/dispatch',
    status: 'active',
    is_enabled: true,
    records_count: 2150,
    last_synced_at: new Date(Date.now() - 8 * 60000).toISOString(),
    config: { priority_filter: 'all', transcript_search: true },
    data_origin: 'synthetic',
    created_at: '2026-09-28T04:00:00Z',
    updated_at: '2026-09-30T06:15:00Z',
  },
  {
    id: 'conn-ngo-01',
    name: 'Allied Humanitarian NGOs & Field Volunteers Consortium',
    source_type: 'ngo',
    adapter_key: 'mock_ngo',
    endpoint_url: 'https://portal.humanitariancoalition.org/api/sightings',
    status: 'active',
    is_enabled: true,
    records_count: 640,
    last_synced_at: new Date(Date.now() - 15 * 60000).toISOString(),
    config: { verified_volunteers_only: true },
    data_origin: 'synthetic',
    created_at: '2026-09-28T04:00:00Z',
    updated_at: '2026-09-30T05:50:00Z',
  },
];

export const SEED_CASES: MissingPersonCase[] = [
  {
    id: 'case-arun-001',
    case_number: 'CASE-2026-0842',
    status: 'under_investigation',
    priority: 'urgent',
    full_name: 'Arun Kumar',
    alias: 'Arun',
    age: 22,
    gender: 'Male',
    last_known_location: 'Sellur Vaigai Bank, Madurai',
    district: 'Madurai',
    last_seen_date: '2026-09-29',
    last_seen_time: '19:30',
    clothing_description: 'Royal blue collared cotton shirt, dark navy trousers, brown sandals',
    height_cm: 174,
    distinguishing_marks: 'Distinct 4cm surgical scar on back of left hand near index metacarpal',
    medical_conditions: 'Mild asthma, carries no inhaler on person',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    reporter_name: 'Suresh Kumar',
    reporter_relationship: 'Elder Brother',
    reporter_phone: '+91-98401-84729',
    reporter_email: 'suresh.k.madurai@gmail.com',
    data_origin: 'synthetic',
    created_at: '2026-09-29T20:45:00Z',
    updated_at: '2026-09-30T06:40:00Z',
  },
  {
    id: 'case-priya-002',
    case_number: 'CASE-2026-0843',
    status: 'awaiting_review',
    priority: 'high',
    full_name: 'Priya Sundaram',
    alias: 'Priya',
    age: 19,
    gender: 'Female',
    last_known_location: 'Central Bus Stand, Trichy',
    district: 'Tiruchirappalli',
    last_seen_date: '2026-09-29',
    last_seen_time: '16:00',
    clothing_description: 'Maroon floral kurti with cream leggings, black backpack with yellow ribbon',
    height_cm: 160,
    distinguishing_marks: 'Small birthmark near right earlobe, silver chain with pendant',
    medical_conditions: 'None',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    reporter_name: 'Sundaram Natarajan',
    reporter_relationship: 'Father',
    reporter_phone: '+91-94432-11894',
    reporter_email: 'sundaram.natarajan@outlook.com',
    data_origin: 'synthetic',
    created_at: '2026-09-29T18:15:00Z',
    updated_at: '2026-09-30T06:20:00Z',
  },
  {
    id: 'case-meenakshi-003',
    case_number: 'CASE-2026-0844',
    status: 'submitted',
    priority: 'urgent',
    full_name: 'Meenakshi Raman',
    alias: 'Meena Amma',
    age: 64,
    gender: 'Female',
    last_known_location: 'Palani Temple Foothill Area, Dindigul',
    district: 'Dindigul',
    last_seen_date: '2026-09-29',
    last_seen_time: '14:20',
    clothing_description: 'Green cotton saree with red border, spectacles with brown frame',
    height_cm: 152,
    distinguishing_marks: 'Difficulty walking without walking stick, memory disorientation',
    medical_conditions: 'Type-2 Diabetes, mild cognitive impairment/dementia',
    photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    reporter_name: 'Anand Raman',
    reporter_relationship: 'Son',
    reporter_phone: '+91-98840-77213',
    reporter_email: 'anand.raman@chennai.biz',
    data_origin: 'synthetic',
    created_at: '2026-09-29T16:00:00Z',
    updated_at: '2026-09-30T05:10:00Z',
  },
  {
    id: 'case-karthik-004',
    case_number: 'CASE-2026-0845',
    status: 'reunited',
    priority: 'medium',
    full_name: 'Karthik Raja',
    alias: 'Karthik',
    age: 8,
    gender: 'Male',
    last_known_location: 'Silver Beach Relief Camp, Cuddalore',
    district: 'Cuddalore',
    last_seen_date: '2026-09-28',
    last_seen_time: '11:00',
    clothing_description: 'Yellow cartoon graphic t-shirt, blue shorts',
    height_cm: 122,
    distinguishing_marks: 'Scar on right knee from bicycle fall',
    medical_conditions: 'None',
    photo_url: 'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?w=400&auto=format&fit=crop&q=80',
    reporter_name: 'Kavitha Raja',
    reporter_relationship: 'Mother',
    reporter_phone: '+91-97910-33445',
    reporter_email: 'kavitha.raja@gmail.com',
    data_origin: 'synthetic',
    created_at: '2026-09-28T12:30:00Z',
    updated_at: '2026-09-29T21:00:00Z',
  },
];

export const SEED_SOURCE_RECORDS: SourceRecord[] = [
  // Record 1: Madurai Shelter (Candidate SH-007)
  {
    id: 'rec-sh-007',
    connection_id: 'conn-shelter-01',
    external_id: 'SH-007',
    source_type: 'shelter',
    source_name: 'Sellur Government Higher Secondary Relief Camp, Madurai',
    person_name: 'Arun (unregistered badge)',
    estimated_age: 23,
    gender: 'Male',
    location_name: 'Sellur Relief Camp #4, Madurai',
    district: 'Madurai',
    recorded_at: '2026-09-29T20:10:00Z', // 8:10 PM Madurai
    clothing_summary: 'Blue collared shirt, dark pants, muddy footwear',
    identifying_marks: 'Clear surgical scar observed on left dorsal hand',
    wristband_tag: 'WB-1842',
    status_condition: 'Stable, exhausted, receiving warm meal and shelter intake bed #42',
    contact_officer: 'Inspector Thangavel (SDMA Relief Coordinator)',
    raw_payload: {
      intake_notes: 'Young male arrived on foot after water level surged near Sellur rail bridge. Reported name Arun.',
      bed_assigned: 'Camp-B-42',
    },
    data_origin: 'synthetic',
    created_at: '2026-09-29T20:12:00Z',
    updated_at: '2026-09-29T20:12:00Z',
  },
  // Record 2: Madurai Hospital (Candidate HP-015)
  {
    id: 'rec-hp-015',
    connection_id: 'conn-hospital-01',
    external_id: 'HP-015',
    source_type: 'hospital',
    source_name: 'Government Rajaji Hospital (GRH) Emergency Ward, Madurai',
    person_name: 'Unknown Male #15',
    estimated_age: 22,
    gender: 'Male',
    location_name: 'GRH Trauma Block, Madurai',
    district: 'Madurai',
    recorded_at: '2026-09-29T21:00:00Z',
    clothing_summary: 'Grey tee shirt, blue jeans',
    identifying_marks: 'No visible scars recorded upon initial admission triage',
    wristband_tag: 'GRH-9921',
    status_condition: 'Under observation for minor contusion, conscious and speaking',
    contact_officer: 'Dr. S. Meenakshisundaram (CMO on duty)',
    raw_payload: { triage_category: 'Green (Minor)', admission_time: '21:00' },
    data_origin: 'synthetic',
    created_at: '2026-09-29T21:05:00Z',
    updated_at: '2026-09-29T21:05:00Z',
  },
  // Record 3: Theni Hospital (Candidate HP-099) - Contradiction with SH-007
  {
    id: 'rec-hp-099',
    connection_id: 'conn-hospital-01',
    external_id: 'HP-099',
    source_type: 'hospital',
    source_name: 'Theni Government Medical College Hospital (TGMCH), Theni',
    person_name: 'Patient Assigned Tag WB-1842',
    estimated_age: 28,
    gender: 'Male',
    location_name: 'TGMCH Triage Bay 2, Theni',
    district: 'Theni',
    recorded_at: '2026-09-29T19:45:00Z', // 7:45 PM Theni
    clothing_summary: 'Green shirt, beige trousers',
    identifying_marks: 'Burn mark on right shoulder',
    wristband_tag: 'WB-1842', // Contradictory wristband re-use/clash!
    status_condition: 'Admitted with waterborne laceration',
    contact_officer: 'Sister Mary Rani (Emergency Intake Supervisor)',
    raw_payload: {
      alert: 'Wristband WB-1842 recorded at 19:45 in Theni. Distance from Madurai is 75km.',
      origin_vehicle: 'Ambulance Unit TN-57-G-4421',
    },
    data_origin: 'synthetic',
    created_at: '2026-09-29T19:50:00Z',
    updated_at: '2026-09-29T19:50:00Z',
  },
  // Record 4: Helpline call record
  {
    id: 'rec-hl-304',
    connection_id: 'conn-helpline-01',
    external_id: 'HL-304',
    source_type: 'helpline',
    source_name: 'SDMA 1070 Disaster Helpline Madurai Desk',
    person_name: 'Caller reporting brother Arun',
    estimated_age: 22,
    gender: 'Male',
    location_name: 'Vaigai River North Bank, Madurai',
    district: 'Madurai',
    recorded_at: '2026-09-29T20:00:00Z',
    clothing_summary: 'Blue shirt, dark pants',
    identifying_marks: 'Scar on left hand',
    wristband_tag: undefined,
    status_condition: 'Sighting reported by bystander seeing youth walking toward Sellur School',
    contact_officer: 'Agent #402 (Helpline Operator)',
    raw_payload: { caller_id: 'CONFIDENTIAL', call_duration_sec: 145 },
    data_origin: 'synthetic',
    created_at: '2026-09-29T20:02:00Z',
    updated_at: '2026-09-29T20:02:00Z',
  },
  // Record 5: NGO volunteer log for Priya
  {
    id: 'rec-ngo-118',
    connection_id: 'conn-ngo-01',
    external_id: 'NGO-118',
    source_type: 'ngo',
    source_name: 'Red Cross Relief Station, Chathiram, Trichy',
    person_name: 'Priya S.',
    estimated_age: 19,
    gender: 'Female',
    location_name: 'Chathiram Bus Stand Transit Camp, Trichy',
    district: 'Tiruchirappalli',
    recorded_at: '2026-09-29T17:30:00Z',
    clothing_summary: 'Maroon floral kurti, yellow ribbon bag',
    identifying_marks: 'Small birthmark right earlobe, silver chain',
    wristband_tag: 'RC-TR-881',
    status_condition: 'Safe, waiting for family contact to establish cell link',
    contact_officer: 'Volunteer Deepak S.',
    raw_payload: { verified_by_coordinator: true },
    data_origin: 'synthetic',
    created_at: '2026-09-29T17:40:00Z',
    updated_at: '2026-09-29T17:40:00Z',
  },
];

export const SEED_CANDIDATES: Candidate[] = [
  {
    id: 'cand-arun-sh007',
    case_id: 'case-arun-001',
    source_record_id: 'rec-sh-007',
    candidate_code: 'SH-007',
    source_type: 'shelter',
    source_name: 'Sellur Government Relief Camp, Madurai',
    match_score: 50.0,
    score_breakdown: {
      id_match: 0, // Wristband WB-1842 not known in initial report
      age_compat: 15, // Age 23 vs 22 (within ±2 years)
      location: 15, // Same district: Madurai
      time: 10, // 8:10 PM vs 7:30 PM (40 min plausible transit)
      clothing: 10, // Blue shirt matched
      marks: 0, // Marks unrecorded in initial shelter log
      name_similarity: 0, // Unrecorded intake
      contradiction_penalty: 0,
      total: 50.0,
      notes: [
        'Age compatible: 23 yrs within ±2 of 22 yrs (+15)',
        'District exact match: Madurai (+15)',
        'Time compatible: 40 min post last-seen (+10)',
        'Clothing match: Blue shirt (+10)',
      ],
    },
    has_contradictions: false,
    contradictions_count: 0,
    status: 'investigating',
    data_origin: 'synthetic',
    created_at: '2026-09-29T20:20:00Z',
    updated_at: '2026-09-30T06:30:00Z',
  },
  {
    id: 'cand-arun-hp015',
    case_id: 'case-arun-001',
    source_record_id: 'rec-hp-015',
    candidate_code: 'HP-015',
    source_type: 'hospital',
    source_name: 'Government Rajaji Hospital Emergency Ward, Madurai',
    match_score: 40.0,
    score_breakdown: {
      id_match: 0,
      age_compat: 15, // Age 22 exact match
      location: 15, // Madurai
      time: 10, // 21:00 (1.5 hrs after last seen)
      clothing: 0, // Unrecorded
      marks: 0, // No scars noted
      name_similarity: 0, // Unknown Male
      contradiction_penalty: 0,
      total: 40.0,
      notes: [
        'Age compatible: exact 22 years (+15)',
        'District match: Madurai (+15)',
        'Time compatible (+10)',
        'Weak initial match pending detailed physical verification',
      ],
    },
    has_contradictions: false,
    contradictions_count: 0,
    status: 'investigating',
    data_origin: 'synthetic',
    created_at: '2026-09-29T21:10:00Z',
    updated_at: '2026-09-30T04:15:00Z',
  },
  {
    id: 'cand-arun-hp099',
    case_id: 'case-arun-001',
    source_record_id: 'rec-hp-099',
    candidate_code: 'HP-099',
    source_type: 'hospital',
    source_name: 'Theni Government Medical College Hospital, Theni',
    match_score: 15.0, // Reduced from 40 due to contradiction penalty (-25)
    score_breakdown: {
      id_match: 30, // Matched wristband tag WB-1842
      age_compat: 0, // 28 vs 22 (outside ±2 yrs)
      location: 0, // Theni vs Madurai (different district)
      time: 10, // Temporal record exists
      clothing: 0, // Green shirt
      marks: 0, // Burn mark vs surgical scar
      name_similarity: 0,
      contradiction_penalty: -25, // Contradiction with Madurai timeline!
      total: 15.0,
      notes: [
        'Tag WB-1842 match (+30)',
        'Age mismatch: 28 yrs vs 22 yrs (0)',
        'District mismatch: Theni vs Madurai (0)',
        'Major physical contradiction penalty applied: -25 points',
        'Travel feasibility: 75km in 25 min implies 180 km/h transit during flood conditions',
      ],
    },
    has_contradictions: true,
    contradictions_count: 1,
    status: 'under_review',
    data_origin: 'synthetic',
    created_at: '2026-09-29T21:15:00Z',
    updated_at: '2026-09-30T06:35:00Z',
  },
  {
    id: 'cand-priya-ngo118',
    case_id: 'case-priya-002',
    source_record_id: 'rec-ngo-118',
    candidate_code: 'NGO-118',
    source_type: 'ngo',
    source_name: 'Red Cross Relief Station, Trichy',
    match_score: 95.0,
    score_breakdown: {
      id_match: 0,
      age_compat: 15,
      location: 15,
      time: 10,
      clothing: 10,
      marks: 15,
      name_similarity: 20,
      contradiction_penalty: 0,
      total: 95.0,
      notes: [
        'Exact age: 19 yrs (+15)',
        'Same district: Trichy (+15)',
        'Time feasible (+10)',
        'Clothing match: Maroon floral kurti (+10)',
        'Distinct marks: Earlobe birthmark & silver chain confirmed (+15)',
        'Name match: Priya S. (+20)',
      ],
    },
    has_contradictions: false,
    contradictions_count: 0,
    status: 'under_review',
    data_origin: 'synthetic',
    created_at: '2026-09-29T18:00:00Z',
    updated_at: '2026-09-30T06:20:00Z',
  },
];

export const SEED_INVESTIGATIONS: Investigation[] = [
  {
    id: 'inv-arun-01',
    case_id: 'case-arun-001',
    state: 'needs_reassessment',
    current_phase: 'contradiction_reflection',
    summary:
      'Candidate SH-007 in Madurai presents an 85% evidence match with matching scars and clothing. However, a wristband clash with HP-099 in Theni was detected, indicating impossible physical velocity (180 km/h). System has reflected on the contradiction and flagged records for human supervisory verification.',
    total_candidates: 3,
    verified_candidates: 2,
    flagged_contradictions: 1,
    data_origin: 'synthetic',
    created_at: '2026-09-29T20:50:00Z',
    updated_at: '2026-09-30T06:40:00Z',
  },
  {
    id: 'inv-priya-01',
    case_id: 'case-priya-002',
    state: 'awaiting_human_review',
    current_phase: 'human_review',
    summary:
      'High-confidence candidate NGO-118 identified at Red Cross Relief Camp, Trichy. All biological and personal tokens reconciled with 95% match score. Ready for official human sign-off.',
    total_candidates: 1,
    verified_candidates: 1,
    flagged_contradictions: 0,
    data_origin: 'synthetic',
    created_at: '2026-09-29T18:30:00Z',
    updated_at: '2026-09-30T06:20:00Z',
  },
];

export const SEED_INVESTIGATION_STEPS: InvestigationStep[] = [
  {
    id: 'step-01',
    investigation_id: 'inv-arun-01',
    step_order: 1,
    phase: 'plan',
    action_name: 'Initial Context Formulation',
    reasoning:
      'Missing person Arun (age 22) last seen in Madurai at 7:30 PM. Priority 1 is searching authorized shelter registries in Madurai district for matching age, blue shirt, and surgical hand scar.',
    created_at: '2026-09-29T20:51:00Z',
  },
  {
    id: 'step-02',
    investigation_id: 'inv-arun-01',
    step_order: 2,
    phase: 'tool_call',
    action_name: 'Execute Shelter Registry Query',
    tool_name: 'search_shelter',
    tool_input: {
      district: 'Madurai',
      age_range: [20, 24],
      gender: 'Male',
      keywords: ['blue shirt', 'scar left hand'],
    },
    reasoning: 'Dispatching authorized query to SDMA ShelterNet API.',
    created_at: '2026-09-29T20:52:00Z',
  },
  {
    id: 'step-03',
    investigation_id: 'inv-arun-01',
    step_order: 3,
    phase: 'tool_result',
    action_name: 'Normalize Shelter Records',
    tool_name: 'search_shelter',
    tool_output: {
      records_found: 1,
      record_id: 'SH-007',
      location: 'Sellur Relief Camp #4, Madurai',
      intake_time: '20:10',
      tag: 'WB-1842',
    },
    reasoning: 'Record SH-007 normalized. Hand scar and blue shirt match reporter description.',
    created_at: '2026-09-29T20:53:00Z',
  },
  {
    id: 'step-04',
    investigation_id: 'inv-arun-01',
    step_order: 4,
    phase: 'tool_call',
    action_name: 'Execute Hospital Network Query',
    tool_name: 'search_hospital',
    tool_input: {
      district: 'Madurai',
      wristband_tag: 'WB-1842',
      expand_nearby_districts: true,
    },
    reasoning:
      'Querying HIMS hospital database to cross-reference wristband WB-1842 across medical intake bays.',
    created_at: '2026-09-29T20:55:00Z',
  },
  {
    id: 'step-05',
    investigation_id: 'inv-arun-01',
    step_order: 5,
    phase: 'verify',
    action_name: 'Deterministic Verification & Contradiction Check',
    reasoning:
      'Mathematical verification detected spatiotemporal conflict: WB-1842 logged at Theni TGMCH at 19:45 and Madurai Shelter at 20:10. Distance 75.2km requires 180 km/h transit. Flagged contradiction and adjusted HP-099 score by -25.',
    created_at: '2026-09-29T20:58:00Z',
  },
  {
    id: 'step-06',
    investigation_id: 'inv-arun-01',
    step_order: 6,
    phase: 'reflect',
    action_name: 'Agent Reflection on Wristband Discrepancy',
    reasoning:
      'Observation: The physical characteristics of SH-007 (scar, blue shirt, age 23, name Arun) match with 85% confidence in Madurai. HP-099 in Theni has a 28yo patient with a burn mark, not a scar. Hypothesis: The wristband WB-1842 was duplicated or misrecorded. The LLM must not override physical facts; human review is required.',
    reflection_notes:
      'Contradiction is likely bureaucratic (duplicate wristband batch or data entry delay). Candidate SH-007 remains the prime suspect for Arun.',
    created_at: '2026-09-29T21:00:00Z',
  },
  {
    id: 'step-07',
    investigation_id: 'inv-arun-01',
    step_order: 7,
    phase: 'replan',
    action_name: 'Targeted Re-query of Madurai Helpline Logs',
    tool_name: 'search_helpline',
    tool_input: { district: 'Madurai', time_window: ['19:30', '21:00'] },
    reasoning:
      'Re-planning to query citizen helpline calls to substantiate whether Arun walked toward Sellur School on foot.',
    created_at: '2026-09-29T21:05:00Z',
  },
];

export const SEED_AGENT_EVENTS: AgentEvent[] = [
  {
    id: 'evt-01',
    case_id: 'case-arun-001',
    investigation_id: 'inv-arun-01',
    event_type: 'agent_started',
    headline: 'Autonomous Investigation Agent Initialized',
    description: 'Investigation initiated for CASE-2026-0842 (Arun Kumar). Tool allowlist active.',
    created_at: '2026-09-29T20:50:00Z',
  },
  {
    id: 'evt-02',
    case_id: 'case-arun-001',
    investigation_id: 'inv-arun-01',
    event_type: 'tool_called',
    headline: 'Tool Invocation: search_shelter',
    description: 'Target: SDMA ShelterNet. Query params: Madurai, Age 20-24, Male.',
    created_at: '2026-09-29T20:52:00Z',
  },
  {
    id: 'evt-03',
    case_id: 'case-arun-001',
    investigation_id: 'inv-arun-01',
    event_type: 'score_calculated',
    headline: 'Candidate SH-007 Scored: 85% Evidence-Based Match',
    description: 'Deterministic scoring engine awarded points for Age (+15), Location (+15), Scar (+15), Shirt (+10), Name (+20).',
    created_at: '2026-09-29T20:54:00Z',
  },
  {
    id: 'evt-04',
    case_id: 'case-arun-001',
    investigation_id: 'inv-arun-01',
    event_type: 'contradiction_detected',
    headline: 'Spatiotemporal Contradiction Detected',
    description: 'Wristband WB-1842 recorded at Theni (19:45) and Madurai (20:10). Distance 75.2km, required speed 180 km/h.',
    payload: { speed_kmh: 180.5, distance_km: 75.2 },
    created_at: '2026-09-29T20:58:00Z',
  },
  {
    id: 'evt-05',
    case_id: 'case-arun-001',
    investigation_id: 'inv-arun-01',
    event_type: 'agent_reflected',
    headline: 'Agent Reflected on Contradiction',
    description: 'Agent concluded wristband anomaly does not invalidate physical matches of SH-007. Re-planning recommended.',
    created_at: '2026-09-29T21:01:00Z',
  },
  {
    id: 'evt-06',
    case_id: 'case-arun-001',
    investigation_id: 'inv-arun-01',
    event_type: 'agent_replanned',
    headline: 'Investigation Plan Revised',
    description: 'Secondary query to 1070 Helpline dispatched to corroborate Sellur foot transit.',
    created_at: '2026-09-29T21:05:00Z',
  },
  {
    id: 'evt-07',
    case_id: 'case-arun-001',
    investigation_id: 'inv-arun-01',
    event_type: 'human_review_requested',
    headline: 'Case Escalated to Human Review Desk',
    description: 'System principle enforced: "The LLM reasons. The system verifies. The human decides."',
    created_at: '2026-09-30T06:30:00Z',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-01',
    case_id: 'case-arun-001',
    actor_name: 'Suresh Kumar',
    actor_role: 'reporter',
    action: 'case_created',
    entity_type: 'cases',
    entity_id: 'case-arun-001',
    details: { case_number: 'CASE-2026-0842', missing_person: 'Arun Kumar' },
    ip_address: '106.198.112.45',
    created_at: '2026-09-29T20:45:00Z',
  },
  {
    id: 'audit-02',
    case_id: 'case-arun-001',
    actor_name: 'Inspector Anand (Lead Investigator)',
    actor_role: 'investigator',
    action: 'investigation_started',
    entity_type: 'investigations',
    entity_id: 'inv-arun-01',
    details: { automated_pipeline_initiated: true },
    ip_address: '10.0.4.12',
    created_at: '2026-09-29T20:50:00Z',
  },
  {
    id: 'audit-03',
    case_id: 'case-arun-001',
    actor_name: 'Reunify Autonomous Agent',
    actor_role: 'investigator',
    action: 'tool_called',
    entity_type: 'source_connections',
    entity_id: 'conn-shelter-01',
    details: { tool: 'search_shelter', target_district: 'Madurai' },
    ip_address: 'internal-agent',
    created_at: '2026-09-29T20:52:00Z',
  },
  {
    id: 'audit-04',
    case_id: 'case-arun-001',
    actor_name: 'Deterministic Verification Engine',
    actor_role: 'admin',
    action: 'score_calculated',
    entity_type: 'candidates',
    entity_id: 'cand-arun-sh007',
    details: { score: 85.0, breakdown: 'Age:15, Loc:15, Time:10, Clothes:10, Scar:15, Name:20' },
    ip_address: 'internal-engine',
    created_at: '2026-09-29T20:54:00Z',
  },
  {
    id: 'audit-05',
    case_id: 'case-arun-001',
    actor_name: 'Contradiction Service',
    actor_role: 'admin',
    action: 'contradiction_detected',
    entity_type: 'candidates',
    entity_id: 'cand-arun-hp099',
    details: {
      type: 'velocity_impossibility',
      speed: '180.5 km/h',
      records: ['SH-007', 'HP-099'],
    },
    ip_address: 'internal-service',
    created_at: '2026-09-29T20:58:00Z',
  },
  {
    id: 'audit-06',
    case_id: 'case-arun-001',
    actor_name: 'Reunify Agent Reflection',
    actor_role: 'investigator',
    action: 'agent_reflected',
    entity_type: 'investigations',
    entity_id: 'inv-arun-01',
    details: { state: 'needs_reassessment', note: 'Wristband clash flagged for supervisory review' },
    ip_address: 'internal-agent',
    created_at: '2026-09-29T21:01:00Z',
  },
  {
    id: 'audit-07',
    case_id: 'case-priya-002',
    actor_name: 'Dr. V. Radhakrishnan (SDMA Reviewer)',
    actor_role: 'reviewer',
    action: 'human_review_requested',
    entity_type: 'review_decisions',
    entity_id: 'cand-priya-ngo118',
    details: { status: 'awaiting_signature', confidence: 'high' },
    ip_address: '10.0.8.22',
    created_at: '2026-09-30T06:20:00Z',
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    case_id: 'case-arun-001',
    title: 'Contradiction Detected in Case Arun Kumar',
    message: 'Wristband WB-1842 has conflicting records in Madurai and Theni requiring reviewer attention.',
    type: 'warning',
    is_read: false,
    created_at: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: 'notif-02',
    case_id: 'case-priya-002',
    title: 'Candidate Ready for Final Human Review',
    message: 'Candidate NGO-118 scored 95% evidence match for Priya Sundaram. Ready for sign-off.',
    type: 'info',
    is_read: false,
    created_at: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: 'notif-03',
    case_id: 'case-karthik-004',
    title: 'Family Reunification Confirmed',
    message: 'Karthik Raja successfully reunited with mother Kavitha Raja at Cuddalore Camp.',
    type: 'success',
    is_read: true,
    created_at: new Date(Date.now() - 300 * 60000).toISOString(),
  },
];
